// Design Tokens - Auto-generated TypeScript Definitions
// Do not edit this file manually

export interface Colors {
  primary: {
    "50": string;
    "100": string;
    "200": string;
    "300": string;
    "400": string;
    "500": string;
    "600": string;
    "700": string;
    "800": string;
    "900": string;
  };
  gray: {
    "50": string;
    "100": string;
    "200": string;
    "300": string;
    "400": string;
    "500": string;
    "600": string;
    "700": string;
    "800": string;
    "900": string;
  };
  success: {
    "50": string;
    "100": string;
  };
  warning: {
    "50": string;
    "100": string;
  };
  error: {
    "50": string;
    "100": string;
    "200": string;
    "300": string;
  };
  info: {
    "50": string;
    "100": string;
  };
  neutral: {
    "50": string;
    "100": string;
    "200": string;
    "300": string;
  };
  text: {
    "primary": string;
    "secondary": string;
    "tertiary": string;
    "inverse": string;
    "muted": string;
  };
  background: {
    "primary": string;
    "secondary": string;
    "tertiary": string;
    "inverse": string;
  };
  border: {
    "default": string;
    "hover": string;
    "focus": string;
    "light": string;
  };
  brand: {
    "primary": string;
    "secondary": string;
    "tertiary": string;
  };
  feedback: {
    "success": string;
    "success-bg": string;
    "warning": string;
    "warning-bg": string;
    "error": string;
    "error-bg": string;
    "info": string;
    "info-bg": string;
    "neutral": string;
    "neutral-bg": string;
  };
}

export interface Spacing {
  "0": string;
  "1": string;
  "2": string;
  "3": string;
  "4": string;
  "5": string;
  "6": string;
  "8": string;
  "10": string;
  "12": string;
  "16": string;
  "20": string;
  "24": string;
}

export interface Typography {
  fontFamily: {
    "sans": string;
    "mono": string;
  };
  fontSize: {
    "xs": string;
    "sm": string;
    "base": string;
    "lg": string;
    "xl": string;
    "2xl": string;
    "3xl": string;
    "4xl": string;
    "5xl": string;
  };
  fontWeight: {
    "normal": string;
    "medium": string;
    "semibold": string;
    "bold": string;
  };
  lineHeight: {
    "tight": string;
    "normal": string;
    "relaxed": string;
  };
  letterSpacing: {
  };
}

export interface DesignTokens {
  colors: Colors;
  spacing: Spacing;
  typography: Typography;
  borderRadius: Record<string, string>;
  shadows: Record<string, string>;
  opacity: Record<string, string>;
  zIndex: Record<string, number>;
  transitions: {
    duration: Record<string, string>;
    easing: Record<string, string>;
  };
  breakpoints: Record<string, string>;
  source?: string;
  lastLoaded?: string;
}

// Token value constants
declare const tokens: DesignTokens;
export default tokens;
export const colors: Colors;
export const spacing: Spacing;
export const typography: Typography;
export const borderRadius: Record<string, string>;
export const shadows: Record<string, string>;
export const opacity: Record<string, string>;